name: Build Kivy APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel git zip openjdk-17-jdk wget unzip

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK Build Tools
        run: |
          mkdir -p $HOME/.buildozer/android/platform/android-sdk
          cd $HOME/.buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip -d cmdline-tools
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-34"

      - name: Build APK
        run: |
          buildozer android debug --log-level 2

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-kivy-app
          path: bin/*.apk
